### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by jakubzitny** [rBurgett/system-font-families#9]
Hi @rBurgett, I'm curious what's your take on supporting this library in the future?

We have an internal fork that we use, we've added a bunch of things to improve the functionality. Recently, I added font file type checks based on file header, instead of just extensions. The main reason for it is that TypeKit on Windows removed extensions from the font files. Would you be interested in a PR?

There are some open PRs and issues for a while. So, if you don't have time to maintain this, I'd be happy to help if you make me a contributor (here and on NPM). Another option would be to transfer this repository under [avocode](http://github.com/avocode) namespace — we're actively using it so we do care about the stability, and we have [a bunch of other open-source projects](https://avocode.com/open-source) that we develop/maintain already.

**Comment by rBurgett** [comment]
Hey @jakubzitny, definitely issue that PR and I'll look at it. The main reason that I haven't updated the repo in a while is that I have a client who has been using it heavily and we ended up making changes specific to him and I never took the time to decided what is work committing and what isn't. Seemingly any changes break the API, and I hate to do that. Issue the PR, I'll look at it, and then we can potentially talk about adding you as a contributor.

**Comment by jakubzitny** [comment]
Will do. In the meantime, I already submitted #7 and #8 😉

**Comment by jakubzitny** [comment]
-> #11.
